### PR TITLE
add ui to consul-agent

### PR DESCRIPTION
**Pull request by jnaulty**
Add UI component to consul-agent for client consumption.

### CODE REVIEW

**Comment by progrium** [comment]
This doesn't make sense to me. If you want the UI, run a server.

**Comment by jnaulty** [comment]
Oh. I was under the assumption that client's could, and should host the UI. I see that might not be the case.

**Comment by jnaulty** [comment]
@progrium 
I read about connecting the UI via client instead of server on [Digital Ocean](https://www.digitalocean.com/community/tutorials/how-to-configure-consul-in-a-production-environment-on-ubuntu-14-04)

I assumed that was the preferred method for production deployment. Perhaps DO is wrong, or maybe there are other benefits to making it a server that I am not aware of. Otherwise, it seems like less overhead with the clients popping up with the UI as opposed to creating a server every time you want the UI up.

**Comment by djenriquez** [comment]
IN MY OPINION: 

I definitely see Digital Ocean's view on offloading server actions by putting the UI on the client, but in the ephemeral space, this could be troublesome.

The problem with having a UI on an agent is that there is no guarantee that there will always be agents. Consul agents are meant to be ephemeral and as such, would complicate routing to the UI. Especially in a cloud-environment, you may have 1 agent one hour, then 100 the next. Whereas there will always be servers and a consistent route to your UI.

I don't have any metrics or data, but having used Consul in production for 6 months, the UI is one of the least likely to cause issues compared to the complex system of Serf, API calls etc.

**Comment by justinclayton** [comment]
As of 0.6.1, the UI is now built into consul binary itself, which solves for this concern for everyone regardless of best practices.

**Comment by sstarcher** [comment]
+1 for relying on the consul binaries supplied ui and not installing it any longer

**Comment by progrium** [comment]
Cool, closing this one. Will take a PR to stop adding ui separately.

**Pull request closed without merging**
