### PR TITLE
Adding nagios-plugins package for convenience

### PR DESCRIPTION
**Pull request by NitroPye**
Its very useful to have nagios-plugins in the image for consul checks.

### CODE REVIEW

**Comment by andyzweb** [comment]
builds and launches 
+1

**Comment by progrium** [comment]
How much larger is the image? I want to accept this, but I'd also love a rule for knowing what should be added and what shouldn't. Any ideas?

**Comment by NitroPye** [comment]
After building these are my images

```
mycatisblack/consul-agent              latest              b77be3220f16        About an hour ago   97.15 MB
gliderlabs/consul-agent                latest              b2a7f8711757        13 days ago         38.18 MB
```

Seems a increase in ~58MB

**Comment by NitroPye** [comment]
I can't speak to a rule for what to include or not. We were originally pulling nagios-plugins in and our other checks in via volumes but we ran into missing libraries. I could extend this image instead of modifying it for our needs.

**Comment by exjet** [comment]
Super helpful addition.
+1

**Comment by therealbill** [comment]
-1 Id go with extending it locally instead of bloating the main image. It is more than double the size and the vast majority of users will not likely need/use the nagios plugins.

**Comment by NitroPye** [comment]
@therealbill any info on what other people are using for checks or is the vast majority an anecdotal estimate? We found that the built in consul checks don't work inside the container (or at least we couldn't get them working) so we were forced to only use script checks. Are most people writing their own checks?

**Comment by therealbill** [comment]
@NitroPye I often run thousands of containers and very few are anywhere near breaking into the 100MB plus range. Most are under 30MB. It isn't a "push for a super tiny container" but a resistance to bloat. Nagios is not a requirement for Consul. I've done hundreds of Consul cluster deploys (in and out of containers) and not a single one involves Nagios. Consider your own case: you are only doing it because you couldn't get the built-in ones working. I've never had a problem with this, and I don't see bug reports to that effect either. This points to it not being common. If your scenario of Consul needing Nagios was common these would not be true. There would be blog posts galore about it, criticism of Hashicorp for the failure of Consul to do the service checks it claims to be able to do, and tutorials including Nagios to make the service checks work.

Not a single tutorial I've seen tells the user to install Nagios to make Consul work. Why push it on to people who don't need or use it? If you need it that's fine, just make a Dockerfile which uses this one as base and adds in your additional requirements. That is the Docker way, after all. It isn't any different than wanting to put Apache, HAProxy, or Nginx in front of Consul for IP or other security mechanisms. Sure, you can and if you want to do it in your Docker image. But we shouldn't expect a base image to contain all the things someone *might* want to reasonably use with Consul.

If the built-in consul checks are not working in a container, then that issue needs to be fixed. So I'd recommend reporting that as a bug with details so it can be tracked down and fixed if indeed a bug, or you can discover what you need to do differently for them to work in your setup.

**Comment by faddat** [comment]
I like the idea, I'm going to give it a roll now.

**Comment by NitroPye** [comment]
@therealbill I think you missed a bunch of my points or I communicated the issue improperly.

> Not a single tutorial I've seen tells the user to install Nagios to make Consul work.
Its mentioned on the default docs that Consul is compatible with Nagios checks. 

Anyways I don't want to argue about this. 

Any movement on this or should I just close it?

**Comment by josegonzalez** [comment]
While I like the idea, given that none of the gliderlabs folks actually use nagios and therefore can't really test this, I'm 👎 and closing. You are free to make a derivative image from this one and add nagios support there :)

**Pull request closed without merging**
